
CREATE DATABASE IF NOT EXISTS buli_hub_db CHARACTER SET utf8 COLLATE utf8_general_ci;
USE buli_hub_db;


CREATE TABLE Roles (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(255) NOT NULL
) ENGINE=InnoDB;


CREATE TABLE Users (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Email VARCHAR(255) NOT NULL UNIQUE,
    BirthDate DATETIME NOT NULL,
    PasswordHash VARCHAR(255) NOT NULL,
    Name VARCHAR(255) NOT NULL,
    RoleId INT NOT NULL,
    RegistrationDate DATETIME NOT NULL,
    Status VARCHAR(50) NOT NULL,
    Gender BOOLEAN NOT NULL,
    FOREIGN KEY (RoleId) REFERENCES Roles(Id)
) ENGINE=InnoDB;


CREATE TABLE Locations (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(255) NOT NULL,
    Address VARCHAR(255) NOT NULL,
    Equipment TEXT
) ENGINE=InnoDB;


CREATE TABLE ServiceProviders (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    UserId INT NOT NULL,
    Adoszam VARCHAR(50) NOT NULL,
    Services VARCHAR(255),
    Company BOOLEAN NOT NULL,
    FOREIGN KEY (UserId) REFERENCES Users(Id)
) ENGINE=InnoDB;


CREATE TABLE Events (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(255) NOT NULL,
    Description TEXT,
    StartDate DATETIME NOT NULL,
    EndDate DATETIME NOT NULL,
    ProviderId INT NOT NULL,
    LocationId INT NOT NULL,
    Status VARCHAR(50) NOT NULL,
    FOREIGN KEY (ProviderId) REFERENCES ServiceProviders(Id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (LocationId) REFERENCES Locations(Id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB;

CREATE TABLE Tickets (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    EventId INT NOT NULL,
    UserId INT NOT NULL,
    PurchaseDate DATETIME NOT NULL,
    Price DECIMAL(10, 2) NOT NULL,
    Status VARCHAR(50) NOT NULL,
    FOREIGN KEY (EventId) REFERENCES Events(Id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (UserId) REFERENCES Users(Id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB;


CREATE TABLE Reports (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    ReportedBy INT NOT NULL,
    EventId INT NOT NULL,
    Content TEXT NOT NULL,
    ReportDate DATETIME NOT NULL,
    Status VARCHAR(50) NOT NULL,
    FOREIGN KEY (ReportedBy) REFERENCES Users(Id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (EventId) REFERENCES Events(Id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB;
